# Generated by Django 3.2.7 on 2021-09-26 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_users_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="dob",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="users",
            name="occupation",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
